import { StyleSheet } from "react-native";

const appStyle = StyleSheet.create({
  container: {
    maxWidth: "1140",
    marginHorizontal: "auto",
    flex: 1,
    alignItems: "stretch",
    padding: 20,
  },
  appView: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    rowGap: 10,
    height: "100%",
  },
  buttonText: {
    padding: 10,
    minHeight: 50,
    justifyContent: "center",
    backgroundColor: "blue",
    color: "#fff",
    borderRadius: 10,
    text: {
      color: "#fff",
      fontSize: 15,
    },
  },
  modalContainer: {
    flex: 1,
    alignContent: "center",
    justifyContent: "center",
    padding: 40,
    backgroundColor: "rgba(0,0,0,0.2)",
  },
  modalStyle: {
    maxHeight: 550,
    width: "100%",
    margin: 20,
    backgroundColor: "#3333",
  },
  userItem: {
    paddingVertical: 12,
    margin: 10,
    marginBottom: 12,
    backgroundColor: "#10c5fb",
    paddingHorizontal: 10,
    justifyContent: "center",
    alignItems: "center",
    flexGrow: 1,
  },
  text: {
    color: "#fff",
    fontWeight: "500",
    fontSize: 16,
    textTransform: "capitalize",
  },
  sectionText: {
    textAlign: "center",
  },
  inputContainer: {
    marginBottom: 15,
  },
  textInput: {
    borderColor: "#ccc",
    borderWidth: 0.5,
    padding: 10,
    fontSize: 18,
    color: "#aaa",
    flexGrow: 1,
    marginBottom: 10,
  },
  content: {
    rowGap: 10,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
    marginTop: 10,
  },
  input: {
    borderStyle: "solid",
    borderColor: "gray",
    height: 45,
    padding: 10,
    borderRadius: 8,
    backgroundColor: "#fff",
    width: "100%",
    borderWidth: 1,
  },
  card: {
    borderStyle: "solid",
    borderColor: "#dedede",
    borderWidth: 1,
    width: "100%",
    borderRadius: 4,
    padding: 12,
    shadowColor: "#dfdfde",
    shadowOffset: 5,
    shadowOpacity: 0.3,
    shadowRadius: 15,
  },
  text: {
    fontSize: 25,
    fontWeight: "700",
  },
  containerShadow: {
    padding: 10,
    flex: 1,
    gap: 20,
    boxShadow: "0 0 15px #0003",
    borderRadius: 10,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});
export * from "./tempConverter.style";
export default appStyle;
